
name: CI

on:

  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: waylonwalker/actions-args@d59adfcf9478680a655f6e50fa5615334b0415b2
        with:
          version: '1.0.0'
