
name: CI

on:

  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: waylonwalker/actions-args@af943c021a9c61007988dbe4de4346d166457ae1
